export const SET_LOGGEDIN_USER = 'SET-LOGGEDIN-USER';
export const LOG_OUT = 'LOG-OUT';
export const UPDATE_USER_ADDRESS = 'UPDATE-USER-ADDRESS';
export const SWITCH_LOADING_PROCESS = 'SWITCH-LOADING-PROCESS';
export const ADD_AUTH_STATUS = 'ADD-AUTH-STATUS';